/**
 * js 中 String 对象有以下几种方法：
 * charAt()
 * charCodeAt()
 * concat()
 * endsWith()
 * startsWith()
 * fromCharCode()
 * fromCodePoint()
 * includes()
 * indexOf()
 * lastIndexOf()
 * localeCompare()
 * match()
 * normalize()
 * raw()
 * replace()
 * search()
 * slice()
 * split()
 * substr()
 * substring()
 * toLocaleLowerCase()
 * tolocaleUpperCase()
 * toLowerCase()
 * toUpperCase()
 * trim()
 * trimLeft()
 * trimRight()
 */